export const categories = [
  {
    slug: "abayas",
    name: "Abayas",
    tone: "#2f3033",
    image: "/images/categories/abayas.jpg",
    blurb: "Fluid silhouettes in Japanese Nida, Korean crepe and washed linen.",
    count: "4 Styles",
  },
  {
    slug: "hijabs",
    name: "Hijabs & Shawls",
    tone: "#d6c7b4",
    image: "/images/categories/hijabs.jpg",
    blurb: "Weightless drape, breathable weave and non-slip finishes.",
    count: "4 Styles",
  },
  {
    slug: "kaftans",
    name: "Kaftans",
    tone: "#6c5c72",
    image: "/images/categories/kaftans.jpg",
    blurb: "Hand-finished occasion pieces with tonal metallic embroidery.",
    count: "2 Styles",
  },
  {
    slug: "dresses",
    name: "Modest Dresses",
    tone: "#7b8a86",
    image: "/images/categories/dresses.jpg",
    blurb: "Everyday ease, floor-sweeping cuts and zero-sheer lining.",
    count: "3 Styles",
  },
  {
    slug: "coords",
    name: "Co-ord Sets",
    tone: "#5a5f70",
    image: "/images/categories/coords.jpg",
    blurb: "Longline tunics and relaxed wide-leg trousers in modest harmony.",
    count: "2 Styles",
  },
  {
    slug: "prayerwear",
    name: "Prayer Wear",
    tone: "#a4907a",
    image: "/images/categories/prayerwear.jpg",
    blurb: "Soft brushed cottons and packable travel khimars with matching pouches.",
    count: "2 Styles",
  },
];

export const products = [
  {
    slug: "noor-open-abaya",
    name: "Noor Open Abaya",
    category: "abayas",
    price: 4890,
    mrp: 6200,
    color: "#2f3033",
    colorName: "Charcoal Noir",
    fabric: "Japanese Nida",
    tag: "Bestseller",
    image: "/images/products/noor-open-abaya.jpg",
    opacity: "100% Opaque (Certified Zero-Sheer)",
    wuduFriendly: true,
    silhouette: "Open Abaya with Sash Belt",
    story: "A clean open-front abaya cut long and narrow from genuine Japanese Nida, featuring a matching self-fabric sash belt you can knot or leave loose over a slip.",
    details: [
      "Open front with detachable tailored belt",
      "Full-length sleeve with wudu-friendly cuff",
      "Genuine Japanese Nida with subtle matte lustre",
      "Opaque weave tested under direct sunlight",
      "Includes matching slip dress attachment loop",
    ],
  },
  {
    slug: "sakina-crepe-abaya",
    name: "Sakina Crepe Abaya",
    category: "abayas",
    price: 5290,
    mrp: null,
    color: "#59685c",
    colorName: "Deep Sage",
    fabric: "Korean Crepe",
    tag: "New",
    image: "/images/products/sakina-crepe-abaya.jpg",
    opacity: "100% Opaque (Heavy Drape)",
    wuduFriendly: true,
    silhouette: "Minimalist Column Cut",
    story: "Column-cut with an inverted pressed pleat down the back for regal movement when you walk. Heavy Korean crepe that never clings.",
    details: [
      "Deep concealed side pockets",
      "Inverted back box pleat for graceful stride",
      "Crease-resistant luxury Korean crepe",
      "High jewel neckline with concealed snap buttons",
      "Machine wash cold, drip dry",
    ],
  },
  {
    slug: "layl-linen-abaya",
    name: "Layl Linen Abaya",
    category: "abayas",
    price: 6450,
    mrp: 7900,
    color: "#8a7c68",
    colorName: "Olive Sand",
    fabric: "Washed Pure Linen",
    tag: null,
    image: "/images/products/layl-linen-abaya.jpg",
    opacity: "100% Opaque (Dense Weave)",
    wuduFriendly: false,
    silhouette: "Relaxed Batwing Drop",
    story: "Crafted for warmth and desert heat alike. Washed pure linen that softens with every wear, breathes freely, and never clings to the body.",
    details: [
      "Relaxed dropped shoulder silhouette",
      "Handmade carved wooden button placket",
      "Garment pre-washed for zero shrinkage",
      "Deep practical seam pockets",
      "Breathable natural hollow fibres",
    ],
  },
  {
    slug: "amal-flared-abaya",
    name: "Amal Flared Abaya",
    category: "abayas",
    price: 4290,
    mrp: null,
    color: "#4a4f63",
    colorName: "Ink Midnight Blue",
    fabric: "Firdous Poly Weave",
    tag: "Popular",
    image: "/images/products/amal-flared-abaya.jpg",
    opacity: "100% Opaque",
    wuduFriendly: true,
    silhouette: "Flared Umbrella Silhouette",
    story: "Closed-front, gently flared from the yoke with a generous 110-inch hem sweep. The quintessential effortless abaya to reach for every single day.",
    details: [
      "Pull-on closed front, zero gaping",
      "Elasticated smocked cuffs for quick wudu access",
      "Falls gracefully to the shoe",
      "Anti-static, dust-shedding weave",
    ],
  },

  {
    slug: "hana-modal-hijab",
    name: "Hana Modal Hijab",
    category: "hijabs",
    price: 890,
    mrp: 1190,
    color: "#d6c7b4",
    colorName: "Warm Bone",
    fabric: "100% Sustainable Modal",
    tag: "Bestseller",
    image: "/images/products/hana-modal-hijab.jpg",
    opacity: "Opaque when folded",
    wuduFriendly: true,
    silhouette: "Maxi Scarf Drape",
    story: "The ultimate daily scarf. Sourced from ultra-fine beechwood modal — heavy enough to stay put all day, featherlight enough to forget you are wearing it.",
    details: [
      "Generous 185 × 75 cm dimensions",
      "Fine eyelash raw fringe edge",
      "Matte non-slip micro-texture",
      "Pin-free drape, holds folds without creasing",
    ],
  },
  {
    slug: "rida-georgette-shawl",
    name: "Rida Georgette Shawl",
    category: "hijabs",
    price: 1290,
    mrp: null,
    color: "#a98b5b",
    colorName: "Antique Gold",
    fabric: "Silk-Touch Georgette",
    tag: "Occasion",
    image: "/images/products/rida-georgette-shawl.jpg",
    opacity: "Semi-Opaque (Double Wrap Recommended)",
    wuduFriendly: true,
    silhouette: "Evening Shawl Drape",
    story: "Occasion drape with a whisper of champagne gold lustre. Pins cleanly, frames the face sculpturally, and elevates Jummah and festive gatherings.",
    details: [
      "200 × 80 cm maxi wrap dimensions",
      "Hand-rolled silk edge borders",
      "Subtle metallic filament reflection",
      "Occasion wear, dry clean recommended",
    ],
  },
  {
    slug: "sidra-jersey-hijab",
    name: "Sidra Jersey Hijab",
    category: "hijabs",
    price: 740,
    mrp: 950,
    color: "#3d3b38",
    colorName: "Soft Onyx Black",
    fabric: "Four-Way Cotton Jersey",
    tag: "Pin-Free",
    image: "/images/products/sidra-jersey-hijab.jpg",
    opacity: "100% Opaque",
    wuduFriendly: true,
    silhouette: "Instant Wrap",
    story: "Four-way stretch premium cotton jersey that requires zero pins, zero undercaps, and stays secure through long work shifts, campus walks, and workouts.",
    details: [
      "170 × 60 cm compact stretch cut",
      "Four-way recovery stretch fabric",
      "Instant pin-free styling",
      "Breathable, sweat-wicking natural cotton blend",
    ],
  },
  {
    slug: "misk-chiffon-set",
    name: "Misk Chiffon Trio Box",
    category: "hijabs",
    price: 1990,
    mrp: 2600,
    color: "#c9b1a3",
    colorName: "Rosewood Palette",
    fabric: "Korean Chiffon",
    tag: "Gift Set",
    image: "/images/products/misk-chiffon-set.jpg",
    opacity: "Lightweight Opaque Layer",
    wuduFriendly: true,
    silhouette: "Curated 3-Pack Capsule",
    story: "Three harmonised tonal chiffon hijabs (Rosewood, Sand Taupe, and Soft Blush) presented in a luxury embossed gift box with gold foil accents.",
    details: [
      "Three scarves, each 185 × 70 cm",
      "Airy Korean chiffon with crisp fall",
      "Gold-foil embossed luxury drawer box",
      "Includes complimentary scent card",
    ],
  },

  {
    slug: "zahra-kaftan",
    name: "Zahra Embroidered Kaftan",
    category: "kaftans",
    price: 8900,
    mrp: 11500,
    color: "#6c5c72",
    colorName: "Muted Royal Plum",
    fabric: "Silk-Blend Brocade",
    tag: "Limited Run",
    image: "/images/products/zahra-kaftan.jpg",
    opacity: "100% Opaque (Fully Lined)",
    wuduFriendly: true,
    silhouette: "Regal Moroccan Kaftan Cut",
    story: "Hand-embroidered neckline with antique gold zari thread work and custom sfifa braid. Crafted in strictly limited runs of twenty pieces for Eid and celebratory evenings.",
    details: [
      "Intricate hand-embroidery along neckline & cuffs",
      "Wide bell sleeves with interior modesty snap",
      "Pure crepe lining from shoulder to hem",
      "Detachable gold braided chord belt with tassels",
    ],
  },
  {
    slug: "yasmin-kaftan",
    name: "Yasmin Sleeve Kaftan",
    category: "kaftans",
    price: 7200,
    mrp: null,
    color: "#39473f",
    colorName: "Forest Emerald",
    fabric: "Heavy Satin Crepe",
    tag: "Occasion",
    image: "/images/products/yasmin-kaftan.jpg",
    opacity: "100% Opaque",
    wuduFriendly: true,
    silhouette: "Straight Cut Bell Sleeve",
    story: "Bell sleeve, straight body, with a weighted hem so the silhouette falls with regal poise rather than billowing in breezes.",
    details: [
      "Weighted lead-corded hemline for perfect drape",
      "Concealed back zipper and modesty hook",
      "Full opaque slip lining included",
      "Dry clean recommended",
    ],
  },

  {
    slug: "iman-shirt-dress",
    name: "Iman Poplin Shirt Dress",
    category: "dresses",
    price: 3890,
    mrp: 4900,
    color: "#b8a894",
    colorName: "Desert Camel",
    fabric: "High-Count Cotton Poplin",
    tag: "Bestseller",
    image: "/images/products/iman-shirt-dress.jpg",
    opacity: "100% Opaque",
    wuduFriendly: true,
    silhouette: "A-Line Maxi Shirt Dress",
    story: "Full-length structured shirt dress with high-density cotton poplin. Designed to wear standalone or unbuttoned as a lightweight long duster over trousers.",
    details: [
      "Full button-down placket with mother-of-pearl buttons",
      "Dual deep side seam pockets",
      "Fabric-matched detachable tie belt",
      "High opacity 120 GSM long-staple cotton",
    ],
  },
  {
    slug: "rahma-pleat-dress",
    name: "Rahma Pleat Dress",
    category: "dresses",
    price: 4390,
    mrp: null,
    color: "#7b8a86",
    colorName: "Eucalyptus Mist",
    fabric: "Permanent Pleat Poly Crepe",
    tag: null,
    image: "/images/products/rahma-pleat-dress.jpg",
    opacity: "100% Opaque (Double Bodice)",
    wuduFriendly: true,
    silhouette: "Knife Pleat Dropped Waist",
    story: "Crisp micro-knife pleats cascading from a modest dropped waist. Bounces and floats gracefully when walking, packs completely wrinkle-free for travel.",
    details: [
      "Permanent heat-set micro knife pleats",
      "Double-lined bodice for guaranteed opacity",
      "Concealed side zipper",
      "No iron needed after machine wash",
    ],
  },
  {
    slug: "safa-knit-dress",
    name: "Safa Ribbed Knit Dress",
    category: "dresses",
    price: 3290,
    mrp: 4100,
    color: "#4c4640",
    colorName: "Dark Espresso",
    fabric: "Heavy Viscose Rib Knit",
    tag: "Layering Essential",
    image: "/images/products/safa-knit-dress.jpg",
    opacity: "100% Opaque (Double Knit)",
    wuduFriendly: true,
    silhouette: "Column Layering Maxi",
    story: "The quintessential modest wardrobe base. Ribbed, non-clinging double knit with a modest high neckline that wears comfortably under every open abaya.",
    details: [
      "High mock neck and full wrist coverage",
      "Substantial 320 GSM non-sheer knit",
      "Comfortable vertical rib stretch",
      "Seamless clean hem",
    ],
  },

  {
    slug: "areej-coord",
    name: "Areej Linen Co-ord",
    category: "coords",
    price: 5690,
    mrp: 6900,
    color: "#c2b199",
    colorName: "Oat Cream",
    fabric: "Slub Linen & Viscose Blend",
    tag: "New",
    image: "/images/products/areej-coord.jpg",
    opacity: "100% Opaque",
    wuduFriendly: true,
    silhouette: "Two-Piece Tunic & Wide Trouser",
    story: "A relaxed, below-knee tunic paired with full-cut wide-leg trousers. One thoughtful decision creates a cohesive, ultra-chic modest aesthetic.",
    details: [
      "Longline tunic with side vent slits for movement",
      "High-rise wide-leg trousers with elasticated back waist",
      "Slub linen blend with cooling breathability",
      "Deep side pockets in both pieces",
    ],
  },
  {
    slug: "dua-satin-coord",
    name: "Dua Satin Co-ord",
    category: "coords",
    price: 6490,
    mrp: null,
    color: "#5a5f70",
    colorName: "Slate Ash",
    fabric: "Heavyweight Matte Satin",
    tag: "Occasion",
    image: "/images/products/dua-satin-coord.jpg",
    opacity: "100% Opaque",
    wuduFriendly: true,
    silhouette: "Longline Top & Column Skirt",
    story: "Rich matte satin without harsh shine. Effortless evening elegance for dinner invitations, Jummah celebrations, and family gatherings.",
    details: [
      "Hip-length top with clean jewel neckline",
      "Straight column maxi skirt with concealed side zip",
      "Low-glare matte finish satin",
      "Fully lined skirt with smooth anti-static lining",
    ],
  },

  {
    slug: "salah-prayer-set",
    name: "Salah Two-Piece Prayer Set",
    category: "prayerwear",
    price: 2490,
    mrp: 3200,
    color: "#e0d6c8",
    colorName: "Soft Ivory",
    fabric: "Brushed Organic Cotton",
    tag: "Bestseller",
    image: "/images/products/salah-prayer-set.jpg",
    opacity: "100% Certified Opaque",
    wuduFriendly: true,
    silhouette: "Full Khimar & Elastic Skirt",
    story: "Designed for sacred moments. Soft, silent brushed organic cotton two-piece prayer dress featuring an overhead khimar and floor-sweeping skirt with a drawstring pouch.",
    details: [
      "Full coverage overhead khimar with built-in tie back",
      "Sweeping elastic-waisted skirt fits all heights",
      "Includes matching zip pouch for handbag storage",
      "Ultra-soft, noise-free breathable combed cotton",
    ],
  },
  {
    slug: "barakah-travel-prayer",
    name: "Barakah Travel Prayer Set",
    category: "prayerwear",
    price: 2890,
    mrp: null,
    color: "#8f9a8d",
    colorName: "Pale Sage",
    fabric: "Microfibre Silk Feel",
    tag: "Travel Ready",
    image: "/images/products/barakah-travel-prayer.jpg",
    opacity: "100% Opaque",
    wuduFriendly: true,
    silhouette: "Compact Travel Khimar Set",
    story: "Ultra-compact, crease-resistant microfibre prayer set that folds into a mini 15 × 20 cm pouch. Stash it in your everyday work tote, travel bag, or car glove box.",
    details: [
      "Completely crease-resistant fabric",
      "Folds into miniature matching travel pouch",
      "Water-repellent finish on hem",
      "Machine washable, dries in 30 minutes",
    ],
  },
];

export const sizes = ["XS", "S", "M", "L", "XL", "XXL"];
export const abayaLengths = ["52″ (132 cm)", "54″ (137 cm)", "56″ (142 cm)", "58″ (147 cm)", "60″ (152 cm)"];

export const inr = (n) => "₹" + n.toLocaleString("en-IN");

export const byCategory = (slug) => products.filter((p) => p.category === slug);
export const bySlug = (slug) => products.find((p) => p.slug === slug);

